import "dotenv/config";
import mongoose from "mongoose";
import { connectDB } from "../config/db.js";
import { Category } from "../models/Category.js";
import { Product } from "../models/Product.js";

async function ensureCategories(names) {
  const found = await Category.find({ name: { $in: names } });
  const existing = new Map(found.map((c) => [c.name, c]));
  const toCreate = names
    .filter((n) => !existing.has(n))
    .map((name) => ({ name }));
  if (toCreate.length) {
    const inserted = await Category.insertMany(toCreate);
    inserted.forEach((c) => existing.set(c.name, c));
  }
  return names.map((n) => existing.get(n));
}

async function run() {
  await connectDB(process.env.MONGODB_URI);

  const categoryNames = [
    "Assets",
    "UI",
    "Skins",
    "Music",
    "Accessories",
    "3D Models",
  ];
  const categories = await ensureCategories(categoryNames);

  const pick = (i) => categories[i % categories.length]._id;
  const images = [
    "https://images.unsplash.com/photo-1605901309584-818e25960a8b?q=80&w=1080&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1080&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1080&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1587300003388-59208cc962cb?q=80&w=1080&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=1080&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1542751110-97427bbecf20?q=80&w=1080&auto=format&fit=crop",
  ];

  const base = [
    { title: "Cyber Arena Soundtrack", price: 9.99 },
    { title: "Neon City UI Skins", price: 12.0 },
    { title: "Fantasy Asset Pack", price: 18.0 },
    { title: "RGB Headset V2", price: 39.0 },
    { title: "Sci‑Fi SFX Bundle", price: 15.0 },
    { title: "Racing HUD Kit", price: 16.0 },
    { title: "Open‑World Map Pack", price: 19.0 },
    { title: "Pixel Platformer Pack", price: 11.0 },
    { title: "Arcade Fonts Bundle", price: 8.0 },
    { title: "Battle Royale Icons", price: 10.0 },
    { title: "Controller Stand 3D", price: 17.0 },
  ];

  console.log("🕹  Seeding GAMING products (non-destructive)…");
  let created = 0;
  for (let i = 0; i < base.length; i++) {
    const b = base[i];
    const doc = {
      title: b.title,
      description:
        "Gaming marketplace sample product autogenerated by seedGaming.js",
      price: b.price,
      images: [images[i % images.length]],
      category: pick(i),
      inventory: 25 + i,
      rating: 4 + (i % 3) * 0.2,
      attributes: { platform: ["pc", "xbox", "ps"][i % 3] },
      rubro: "GAMING",
      active: true,
    };
    // Avoid duplicates by title
    const exists = await Product.findOne({ title: doc.title });
    if (!exists) {
      await Product.create(doc);
      created++;
    }
  }

  console.log(`✅ Done. Inserted ${created} new gaming products.`);
  await mongoose.connection.close();
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
